/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/imcsk8/k8s-operators/pkg/apis/testoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTestOperators implements TestOperatorInterface
type FakeTestOperators struct {
	Fake *FakeMyprojectV1alpha1
	ns   string
}

var testoperatorsResource = schema.GroupVersionResource{Group: "myproject", Version: "v1alpha1", Resource: "testoperators"}

var testoperatorsKind = schema.GroupVersionKind{Group: "myproject", Version: "v1alpha1", Kind: "TestOperator"}

// Get takes name of the testOperator, and returns the corresponding testOperator object, and an error if there is any.
func (c *FakeTestOperators) Get(name string, options v1.GetOptions) (result *v1alpha1.TestOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testoperatorsResource, c.ns, name), &v1alpha1.TestOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestOperator), err
}

// List takes label and field selectors, and returns the list of TestOperators that match those selectors.
func (c *FakeTestOperators) List(opts v1.ListOptions) (result *v1alpha1.TestOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testoperatorsResource, testoperatorsKind, c.ns, opts), &v1alpha1.TestOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TestOperatorList{ListMeta: obj.(*v1alpha1.TestOperatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.TestOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testOperators.
func (c *FakeTestOperators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testoperatorsResource, c.ns, opts))

}

// Create takes the representation of a testOperator and creates it.  Returns the server's representation of the testOperator, and an error, if there is any.
func (c *FakeTestOperators) Create(testOperator *v1alpha1.TestOperator) (result *v1alpha1.TestOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testoperatorsResource, c.ns, testOperator), &v1alpha1.TestOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestOperator), err
}

// Update takes the representation of a testOperator and updates it. Returns the server's representation of the testOperator, and an error, if there is any.
func (c *FakeTestOperators) Update(testOperator *v1alpha1.TestOperator) (result *v1alpha1.TestOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testoperatorsResource, c.ns, testOperator), &v1alpha1.TestOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestOperator), err
}

// Delete takes name of the testOperator and deletes it. Returns an error if one occurs.
func (c *FakeTestOperators) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testoperatorsResource, c.ns, name), &v1alpha1.TestOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestOperators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testoperatorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TestOperatorList{})
	return err
}

// Patch applies the patch and returns the patched testOperator.
func (c *FakeTestOperators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testoperatorsResource, c.ns, name, data, subresources...), &v1alpha1.TestOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestOperator), err
}
