/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/imcsk8/k8s-operators/pkg/apis/testoperator/v1alpha1"
	scheme "github.com/imcsk8/k8s-operators/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TestOperatorsGetter has a method to return a TestOperatorInterface.
// A group's client should implement this interface.
type TestOperatorsGetter interface {
	TestOperators(namespace string) TestOperatorInterface
}

// TestOperatorInterface has methods to work with TestOperator resources.
type TestOperatorInterface interface {
	Create(*v1alpha1.TestOperator) (*v1alpha1.TestOperator, error)
	Update(*v1alpha1.TestOperator) (*v1alpha1.TestOperator, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TestOperator, error)
	List(opts v1.ListOptions) (*v1alpha1.TestOperatorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestOperator, err error)
	TestOperatorExpansion
}

// testOperators implements TestOperatorInterface
type testOperators struct {
	client rest.Interface
	ns     string
}

// newTestOperators returns a TestOperators
func newTestOperators(c *MyprojectV1alpha1Client, namespace string) *testOperators {
	return &testOperators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the testOperator, and returns the corresponding testOperator object, and an error if there is any.
func (c *testOperators) Get(name string, options v1.GetOptions) (result *v1alpha1.TestOperator, err error) {
	result = &v1alpha1.TestOperator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testoperators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TestOperators that match those selectors.
func (c *testOperators) List(opts v1.ListOptions) (result *v1alpha1.TestOperatorList, err error) {
	result = &v1alpha1.TestOperatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested testOperators.
func (c *testOperators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("testoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a testOperator and creates it.  Returns the server's representation of the testOperator, and an error, if there is any.
func (c *testOperators) Create(testOperator *v1alpha1.TestOperator) (result *v1alpha1.TestOperator, err error) {
	result = &v1alpha1.TestOperator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("testoperators").
		Body(testOperator).
		Do().
		Into(result)
	return
}

// Update takes the representation of a testOperator and updates it. Returns the server's representation of the testOperator, and an error, if there is any.
func (c *testOperators) Update(testOperator *v1alpha1.TestOperator) (result *v1alpha1.TestOperator, err error) {
	result = &v1alpha1.TestOperator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testoperators").
		Name(testOperator.Name).
		Body(testOperator).
		Do().
		Into(result)
	return
}

// Delete takes name of the testOperator and deletes it. Returns an error if one occurs.
func (c *testOperators) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testoperators").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *testOperators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testoperators").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched testOperator.
func (c *testOperators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestOperator, err error) {
	result = &v1alpha1.TestOperator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("testoperators").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
