/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	testoperator_v1alpha1 "github.com/imcsk8/k8s-operators/pkg/apis/testoperator/v1alpha1"
	versioned "github.com/imcsk8/k8s-operators/pkg/client/clientset/versioned"
	internalinterfaces "github.com/imcsk8/k8s-operators/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/imcsk8/k8s-operators/pkg/client/listers/testoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TestOperatorInformer provides access to a shared informer and lister for
// TestOperators.
type TestOperatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TestOperatorLister
}

type testOperatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestOperatorInformer constructs a new informer for TestOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestOperatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestOperatorInformer constructs a new informer for TestOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MyprojectV1alpha1().TestOperators(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MyprojectV1alpha1().TestOperators(namespace).Watch(options)
			},
		},
		&testoperator_v1alpha1.TestOperator{},
		resyncPeriod,
		indexers,
	)
}

func (f *testOperatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestOperatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testOperatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&testoperator_v1alpha1.TestOperator{}, f.defaultInformer)
}

func (f *testOperatorInformer) Lister() v1alpha1.TestOperatorLister {
	return v1alpha1.NewTestOperatorLister(f.Informer().GetIndexer())
}
